In [ ]:


import numpy as np

# Problem-1 Task 1 Initialize an empty array with size 2X2.
empty_array = np.empty((1, 2))
print("Empty Array 2x2:")
print(empty_array)




Empty Array 2x2:
[[4.68219966e-310 4.68291393e-310]]


In [ ]:
# Task 2: Initialize an all one array with size 4x2
ones_array = np.ones((6, 3))
print("\nAll Ones Array 4x2:")
print(ones_array)


All Ones Array 4x2:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Task 3: Return a new array of given shape and type, filled with a specific fill value
filled_array = np.full((4, 3), 8)
print("\nFilled Array 3x3 with value 7:")
print(filled_array)


Filled Array 3x3 with value 7:
[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [ ]:
# Task 4: Return a new array of zeros with same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Array with same shape as reference array:")
print(zeros_like_array)


Zeros Array with same shape as reference array:
[[0 0]
 [0 0]]


In [5]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:




In [6]:
# Task 1: Create an array with values ranging from 10 to 49
import numpy as np

# Using np.arange() to create an array from 10 to 49
array_1 = np.arange(10, 50)
print("Array from 10 to 49:", array_1)


Array from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# Task 2: Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:")
print(arr2)



3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Task 3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# Task 4: Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30 and its Mean:")
print(random_array)
print("Mean:", mean_value)



Random Array of size 30 and its Mean:
[0.63251293 0.65659352 0.79470301 0.09435308 0.10615092 0.54192041
 0.76271598 0.65084169 0.71400941 0.99733235 0.76363088 0.36499191
 0.22387    0.45611895 0.62244824 0.91504646 0.67627082 0.53528393
 0.37670779 0.90288983 0.68640826 0.86013339 0.61560897 0.48461929
 0.72936747 0.86125684 0.24891719 0.76469769 0.41217567 0.62940691]
Mean: 0.6026994600112681


In [10]:
# Create a 10x10 array with random values
random_array_10x10 = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("Minimum value in 10x10 array:", min_value)
print("Maximum value in 10x10 array:", max_value)


Minimum value in 10x10 array: 0.0011698223163745247
Maximum value in 10x10 array: 0.9984519577649745


In [11]:
# Create a 10x10 array with random values
random_array_10x10 = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("Minimum value in 10x10 array:", min_value)
print("Maximum value in 10x10 array:", max_value)


Minimum value in 10x10 array: 0.0027968464251748593
Maximum value in 10x10 array: 0.9917223005785011


In [12]:
# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1
print("Zero array with 5th element replaced with 1:", zero_array)


Zero array with 5th element replaced with 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# Original array
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse the array
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Reversed array: [0 4 0 0 2 1]


In [14]:
# Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:\n", border_array)


2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 checkerboard pattern:\n", checkerboard)


8x8 checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [16]:
#Task3
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


In [17]:
#1:
# Adding the two arrays x and y
add_result = x + y
print("Addition of x and y:\n", add_result)



Addition of x and y:
 [[ 6  8]
 [10 13]]


In [18]:
# Subtracting the two arrays x and y
subtract_result = x - y
print("Subtraction of x and y:\n", subtract_result)


Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [19]:
# Multiplying array x with an integer, for example, 3
multiply_result = x * 3
print("Multiplication of x with 3:\n", multiply_result)


Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]


In [20]:
# Squaring each element of array x
square_result = np.square(x)
print("Square of each element of x:\n", square_result)


Square of each element of x:
 [[ 1  4]
 [ 9 25]]


In [21]:
# Dot product of v and w
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

# Dot product of x and v
dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

# Dot product of x and y
dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)


Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [22]:
# Concatenate x and y along row (axis 1)
concat_xy_row = np.concatenate((x, y), axis=1)
print("Concatenation of x and y along row:\n", concat_xy_row)

# Concatenate v and w along column (axis 0)
concat_vw_column = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("Concatenation of v and w along column:\n", concat_vw_column)


Concatenation of x and y along row:
 [[1 2 5 6]
 [3 5 7 8]]
Concatenation of v and w along column:
 [[ 9 11]
 [10 12]]


In [23]:
# Trying to concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=1)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [24]:
#Task4
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])



In [25]:
#1. Prove A.A−1 = I.
# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Compute A * A_inv
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 = \n", identity_matrix)



A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [27]:
#2. Prove AB ̸= BA.
# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Print the results
print("AB = \n", AB)
print("BA = \n", BA)


AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]


In [28]:
#3
# Compute (AB)^T
AB_T = np.transpose(AB)

# Compute B^T * A^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))

# Print the results
print("Transpose of AB = \n", AB_T)
print("B^T * A^T = \n", BT_AT)



Transpose of AB = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]


In [29]:
#4.
# Coefficient matrix A
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Constants vector B
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)
print("Solution X = \n", X)


Solution X = 
 [ 2.  1. -2.]
